name: website deployment

on:
  push:
    branches:
     -master

jobs:
  build-jobs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1 #all checkout work done by this , prewriten by github

    - name: Configure AWS Credentials
      uses: aws-actions/comfigure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    - name: Deploy static site to S3 bucket
      run: aws s3 sync . s3://yash168-bucket --delete
        

    
    
